### ISSUE TITLE
Add filter to image position

### ISSUE THREAD

**Issue by Horttcore** [ruiguerreiro79/menu-image#1]
The image position should be filterable.
I wold like to remove all image position and add my own (behind).

Something like this
```php
$positions = apply_filters('menu-image-positions', [
    'hide'   => __( 'Hide', 'menu-image' ),
    'above'  => __( 'Above', 'menu-image' ),
    'below'  => __( 'Below', 'menu-image' ),
    'before' => __( 'Before', 'menu-image' ),
    'after'  => __( 'After', 'menu-image' ),
 ]);
```

**Comment by ruiguerreiro79** [comment]
Hi @Horttcore,
Those options are for the Title position regarding the image. What is the idea with 'behind' do you have a visual example of how it can look?

**Comment by Horttcore** [comment]
The text should be placed on the image.
I would like to remove some options for my clients, as they would only mess them up.
I'm a developer so could code everything by my own, but some hooks here and there would make stuff easier.

**Comment by ruiguerreiro79** [comment]
thanks for the feedback. Sure will add that one, I'm also adding one more to change the HTML of the image if necessary.

If you think there are other places that will be valuable to add some hooks or filter let me know so I can evaluate.

**Comment by Horttcore** [comment]
@ruiguerreiro79 Sure will do that.

**Comment by ruiguerreiro79** [comment]
@Horttcore This feature was added in the #5 
Will release the new version in the WordPress repository in the next hours.

Thanks
